const express=require('express'),path=require('path'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');const {db,officerPhone,officerPassword}=require('./database');const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'change-this-kisansetu-secret';app.use(express.json());app.use(express.static(path.join(__dirname,'public')));const token=u=>jwt.sign(u,SECRET,{expiresIn:'7d'});function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');if(!t)return res.status(401).json({message:'Please login first.'});try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({message:'Session expired. Please login again.'})}}
app.get('/api/health',(q,s)=>s.json({status:'online'}));
app.post('/api/register',async(q,s)=>{let {name,phone,village,password}=q.body;if(!name||!phone||!village||!password)return s.status(400).json({message:'Please fill all fields.'});if(!/^\d{10}$/.test(phone))return s.status(400).json({message:'Phone number must contain 10 digits.'});if(password.length<6)return s.status(400).json({message:'Password must be at least 6 characters.'});if(db.prepare('SELECT id FROM farmers WHERE phone=?').get(phone))return s.status(409).json({message:'This phone number is already registered.'});const r=db.prepare('INSERT INTO farmers(name,phone,village,password) VALUES(?,?,?,?)').run(name.trim(),phone,village.trim(),await bcrypt.hash(password,10));const user={id:r.lastInsertRowid,role:'farmer',name:name.trim(),phone,village:village.trim()};s.status(201).json({token:token(user),user})});
app.post('/api/login',async(q,s)=>{const {phone,password}=q.body,f=db.prepare('SELECT * FROM farmers WHERE phone=?').get(phone);if(!f||!(await bcrypt.compare(password||'',f.password)))return s.status(401).json({message:'Invalid phone number or password.'});const user={id:f.id,role:'farmer',name:f.name,phone:f.phone,village:f.village};s.json({token:token(user),user})});
app.post('/api/officer/login',(q,s)=>{const {phone,password}=q.body;if(phone!==officerPhone||password!==officerPassword)return s.status(401).json({message:'Invalid officer credentials.'});const user={id:1,role:'officer',name:'Procurement Officer',phone};s.json({token:token(user),user})});
app.get('/api/procurements',auth,(q,s)=>{if(q.user.role==='officer')return s.json(db.prepare('SELECT p.*,f.name farmer_name,f.phone,f.village FROM procurements p JOIN farmers f ON f.id=p.farmer_id ORDER BY p.id DESC').all());s.json(db.prepare('SELECT * FROM procurements WHERE farmer_id=? ORDER BY id DESC').all(q.user.id))});
app.post('/api/procurements',auth,(q,s)=>{if(q.user.role!=='farmer')return s.status(403).json({message:'Only farmers can create requests.'});const {crop,quantity}=q.body;if(!crop||!quantity||+quantity<=0)return s.status(400).json({message:'Enter a valid crop and quantity.'});db.prepare('INSERT INTO procurements(farmer_id,crop,quantity) VALUES(?,?,?)').run(q.user.id,crop.trim(),+quantity);s.json({message:'Request submitted.'})});
app.patch('/api/procurements/:id',auth,(q,s)=>{if(q.user.role!=='officer')return s.status(403).json({message:'Only officers can update requests.'});if(!['Pending','Approved','Completed','Rejected'].includes(q.body.status))return s.status(400).json({message:'Invalid status.'});db.prepare('UPDATE procurements SET status=? WHERE id=?').run(q.body.status,q.params.id);s.json({message:'Updated.'})});
app.get('/officer',(q,s)=>s.sendFile(path.join(__dirname,'public','officer.html')));app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log('KisanSetu running on port '+PORT));
